server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://192.168.1.13:3306/test?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tbj
    password: 秘密
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
